export const ERROR_CODES = {
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  REPAIR_STATUS_INVALID: 'REPAIR_STATUS_INVALID',
  PAYMENT_ALREADY_PAID: 'PAYMENT_ALREADY_PAID',
  ANNOUNCEMENT_NOT_FOUND: 'ANNOUNCEMENT_NOT_FOUND',
} as const;
